baseurl = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "oodavid-stellar"

# Code Highlighting
PygmentsCodeFences = true
PygmentsStyle = "monokai"

[params]
  description = "Tesla's Awesome Hugo Site"
  author = "Nikola Tesla"
