baseurl = "https://oodavid.com/"
languageCode = "en-gb"
title = "David King"
theme = "oodavid"
paginate = 5

# Comments
disqusShortname = "oodavid-com"

# Analytics
googleAnalytics = "UA-24181653-1"

# Code Highlighting
PygmentsCodeFences = true
PygmentsStyle = "monokai"

# Markdown
[blackfriday]
  hrefTargetBlank = true
