baseurl = "https://oodavid.com/"
languageCode = "en-gb"
title = "oodavid.com"
theme = "oodavid"
paginate = 8

# Site Params
[params]
  author = "David King"
  title = "David King"
  name = "oodavid.com"
  twitter = "@oodavid"
  image = "/images/oodavid.png"
  description = "A blog about Angular, AngularJS and Firebase"

# Comments
disqusShortname = "oodavid-com"

# Analytics
googleAnalytics = "UA-24181653-1"

# Code Highlighting
PygmentsCodeFences = true
PygmentsStyle = "monokai"

# Markdown
[blackfriday]
  hrefTargetBlank = true
