baseurl = "/"
languageCode = "en-gb"
title = "David King"
theme = "oodavid"
paginate = 5

# Analytics
googleAnalytics = "UA-24181653-1"

# Code Highlighting
PygmentsCodeFences = true
PygmentsStyle = "monokai"
